# Generated by Django 3.1 on 2021-05-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grc_account', '0002_user'),
        ('grc_common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grc_account.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
